import type { Metadata } from "next";
import { Alegreya_Sans, Libre_Franklin, Pontano_Sans } from "next/font/google";
import "./globals.css";
import Breadcrumbs from "./components/Breadcrumbs";

const libre = Libre_Franklin({
  variable: "--font-libre",
  subsets: ["latin"],
});

const alegreya = Alegreya_Sans({
  variable: "--font-alegreya",
  subsets: ["latin"],
  weight: ["400"],
});

const pontano = Pontano_Sans({
  variable: "--font-pontano",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre.variable} ${alegreya.variable} ${pontano.variable} antialiased`}
      >
        <Breadcrumbs />
        {children}
      </body>
    </html>
  );
}
